### ISSUE TITLE
Call to undefined method Container::terminating()

### ISSUE THREAD

**Issue by dogukanoksuz** [beebmx/blade#2]
![Uploading 198253355-469ed2ac-7e02-4d61-a7af-b2cfd5a365e0.png…](https://user-images.githubusercontent.com/32539161/198253355-469ed2ac-7e02-4d61-a7af-b2cfd5a365e0.png)

Pr opened on #1

**Comment by beebmx** [comment]
This is added in [v1.6.2](https://github.com/beebmx/blade/releases/tag/v1.6.2)

Thanks!
